 

export enum ACCOUNT_SETTINGS {
  // ACCOUNT_SETTINGS = "ACCOUNT_SETTINGS",
  // CHANGE_PASSWORD = "CHANGE_PASSWORD",
  // CHANGE_LANGUAGE = "CHANGE_LANGUAGE",
  // ADD_INVITATION_KEY = "ADD_INVITATION_KEY",
}
